import {currentShift} from './work.js';
import {workUI} from './work-ui.js';
import {ritualsUI} from './rituals-ui.js';
import {smartUI} from './smart-ui.js';
import {prepareSmart,calculator} from './smart.js';
import {outingsUI} from './outings-ui.js';
import {isOperating,createDebt,increaseDebt,setDebtArchived,removeTransaction} from './money-flows.js';
import {goalsUI} from './goals-ui.js';
import {dataToolsUI} from './data-tools-ui.js';
import {remindersUI} from './reminders-ui.js';
import {initPwa} from './pwa.js';
import {insightsUI} from './insights-ui.js';
import {financeUI} from './finance-ui.js';
import {today,uid,initial,cents,balance,remaining,addTransaction,validate,migrate} from './model.js';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const eur=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n/100),dateLabel=d=>new Date(d+'T12:00:00').toLocaleDateString('de-DE',{day:'numeric',month:'short'});
let state=initial(),page='home',financeTab='Buchungen',horizon='Tag',showDone=false,debtKind='Alle',debtArchive=false,undo=null,toastTimer;
const affirmations=['Ich muss nicht alles auf einmal verändern. Mein nächster Schritt zählt.','Ich kann meine Finanzen Schritt für Schritt besser verstehen.','Ich darf dazulernen und heute eine bewusste Entscheidung treffen.','Ein kleiner realistischer Schritt bringt mich meinem Ziel näher.','Ich richte meine Aufmerksamkeit auf das, was ich beeinflussen kann.','Ich kann innehalten und bewusst mit meinem Geld umgehen.','Ich erkenne meine Fortschritte an und passe meinen Plan an.'];
const dailyAffirmation=()=>affirmations[Math.floor(Date.parse(today())/86400000)%affirmations.length];
const KEY='klar.v1';let loadError=false;try{const raw=localStorage.getItem(KEY);if(raw)state=migrate(JSON.parse(raw));}catch{loadError=true;}
const paths={home:'M3 10l9-7 9 7v10a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1z M9 21v-8h6v8',wallet:'M3 6h16v14H3z M3 6V4h13v2 M15 11h6v5h-6z',target:'M21 12a9 9 0 1 1-9-9 M17 12a5 5 0 1 1-5-5 M12 12l9-9 M16 3h5v5',spark:'M12 3l2.4 6.6L21 12l-6.6 2.4L12 21l-2.4-6.6L3 12l6.6-2.4z',plus:'M12 5v14 M5 12h14',minus:'M5 12h14',up:'M12 19V5 M5 12l7-7 7 7',down:'M12 5v14 M5 12l7 7 7-7',check:'M5 12l4 4L19 6',bank:'M3 9l9-6 9 6z M5 10v9 M10 10v9 M14 10v9 M19 10v9 M3 21h18',arrow:'M5 12h14 M13 6l6 6-6 6'};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[n]||paths.wallet}"/></svg>`;
function toast(msg,action){clearTimeout(toastTimer);$('#toast').innerHTML=esc(msg)+(action?'<button id="undo">Rückgängig</button>':'');$('#toast').style.display='block';if(action)$('#undo').onclick=action;toastTimer=setTimeout(()=>$('#toast').style.display='none',6000);}
function commit(fn,msg){if(loadError){toast('Bitte zuerst die beschädigten Daten in Einstellungen sichern oder wiederherstellen.');return false;}const before=JSON.stringify(state),original=state;try{fn();prepareSmart(state,state===original?JSON.parse(before):null,today());validate(state);localStorage.setItem(KEY,JSON.stringify(state));}catch(e){state=JSON.parse(before);toast(e.message||'Speichern fehlgeschlagen.');return false;}clearTimeout(toastTimer);$('#toast').style.display='none';undo=null;render();if(msg)toast(msg,()=>{const restored=JSON.parse(before);commit(()=>state=restored,'Änderung rückgängig gemacht');});return true;}
function removeEntry(collection,id){const snapshot=JSON.stringify(state);if(commit(()=>{if(collection==='transactions')removeTransaction(state,id);else state[collection]=state[collection].filter(x=>x.id!==id);})){undo=snapshot;toast('Eintrag gelöscht',()=>{if(undo){const restored=JSON.parse(undo);if(commit(()=>state=restored,'Wiederhergestellt'))undo=null;}});}}
function go(p){page=p;render();window.scrollTo(0,0)}
function title(eyebrow,heading,sub){return `<p class="eyebrow">${eyebrow}</p><h1>${heading}</h1><p class="subtitle">${sub}</p>`}
function headerRow(t,b='',action=''){return `<div class="section-head"><h2>${t}</h2>${b?`<button class="text-button" data-action="${action}">${b}</button>`:''}</div>`}
function accountCards(){return `<div class="grid2">${state.accounts.map(a=>`<button class="card account" data-account="${a.id}"><span class="account-icon">${icon(a.kind==='cash'?'wallet':'bank')}</span><span class="label">${esc(a.name)}</span><span class="account-kind">${a.kind==='cash'?'Bargeld':'Bankkonto / Karte'}</span><strong>${eur(balance(state,a.id))}</strong>${state.outings.some(o=>o.status==='open'&&o.lines.some(l=>l.account===a.id))?'<small class="hint">Ein Budget ist unterwegs vorgemerkt</small>':''}</button>`).join('')}</div>`}
function txRows(list){return list.length?list.map(t=>`<div class="row" data-tx="${t.id}"><span class="row-icon ${t.type==='income'?'positive':''}">${icon(t.type==='income'?'down':'up')}</span><div class="row-body"><strong>${esc(t.note||t.category)}</strong><small>${dateLabel(t.date)} · ${esc(state.accounts.find(a=>a.id===t.account)?.name)} · ${esc(t.category)}</small></div><span class="row-amount ${t.type==='income'?'positive':''}">${t.type==='income'?'+':'−'}${eur(t.amount)}</span><button class="tiny" data-tx-detail="${t.id}" aria-label="Buchung ${esc(t.note||t.category)} bearbeiten">•••</button></div>`).join(''):'<p class="empty">Hier beginnt dein Überblick.<br>Trage deine erste Einnahme oder Ausgabe ein.</p>'}
function chart(){let days=Array.from({length:7},(_,i)=>{let d=new Date();d.setDate(d.getDate()-6+i);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`});const sums=days.map(d=>['income','expense'].map(k=>state.transactions.filter(t=>isOperating(t)&&t.date===d&&t.type===k).reduce((s,t)=>s+t.amount,0)));const max=Math.max(1,...sums.flat());return `<div class="bars" role="img" aria-label="Einnahmen und Ausgaben der letzten sieben Tage">${days.map((d,i)=>`<div class="bar-group" title="${d}: Einnahmen ${eur(sums[i][0])}, Ausgaben ${eur(sums[i][1])}"><div class="bar-pair"><span class="bar" style="height:${sums[i][0]/max*68}px"></span><span class="bar out" style="height:${sums[i][1]/max*68}px"></span></div><small>${new Date(d+'T12:00:00').toLocaleDateString('de-DE',{weekday:'short'})}</small></div>`).join('')}</div><div class="legend"><span><i></i>Einnahmen</span><span><i class="out"></i>Ausgaben</span></div>`}
function home(){const month=today().slice(0,7),sum=k=>state.transactions.filter(t=>isOperating(t)&&t.date.startsWith(month)&&t.type===k).reduce((n,t)=>n+t.amount,0),cashToday=state.transactions.filter(t=>isOperating(t)&&t.date===today()&&state.accounts.find(a=>a.id===t.account)?.kind==='cash'&&t.type==='income').reduce((n,t)=>n+t.amount,0);return title(new Date().toLocaleDateString('de-DE',{weekday:'long',day:'numeric',month:'long'}),'Heute im Blick.<br>Dein Morgen im Plan.','Dein Geld und deine Ziele. An einem Ort.')+`<section class="hero"><div class="hero-label">Dein Gesamtguthaben</div><div class="amount">${eur(state.accounts.reduce((n,a)=>n+balance(state,a.id),0))}</div><small>Alle Konten · manuell erfasst</small><div class="hero-foot"><div><small>↙ Einnahmen · Monat</small><strong>${eur(sum('income'))}</strong></div><div><small>↗ Ausgaben · Monat</small><strong>${eur(sum('expense'))}</strong></div></div></section><div class="grid2"><button class="quick" data-action="income">${icon('plus')}Bargeld eintragen</button><button class="quick secondary" data-action="expense">${icon('minus')}Ausgabe erfassen</button></div><p class="hint" style="text-align:center">Heute bar eingenommen: <strong>${eur(cashToday)}</strong></p>`+smartTools.startCards()+outingTools.summary()+reminderTools.summary()+headerRow('Vorausgeschaut','Zahlungen & Abos','planning')+`<button class="card wide" style="text-align:left" data-action="planning"><h3>Was steht als Nächstes an? &nbsp; →</h3><span class="hint">Erwartete Zahlungen, Abos und offene Rechnungen</span></button>`+headerRow('Deine Konten','Verwalten','accounts')+accountCards()+headerRow('Deine Woche','Statistik öffnen','statistics')+`<div class="card">${chart()}</div>`+headerRow('Ein kleiner Schritt','Alle Ziele','goals')+`<div class="card">${goalRows(state.goals.filter(g=>!g.done).sort((a,b)=>Number(b.pinned)-Number(a.pinned)||(a.due||'9999').localeCompare(b.due||'9999')).slice(0,3))}</div><div class="card focus-card"><p class="eyebrow">DEIN FOKUS FÜR HEUTE</p><p>„${esc(state.beliefs.find(b=>!b.archived)?.text||dailyAffirmation())}“</p><button data-action="focus">Mein täglicher Check-in &nbsp; →</button></div>`+headerRow('Letzte Bewegungen','Alle ansehen','transactions')+`<div class="card">${txRows([...state.transactions].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,4))}</div>`}
function finances(){return title('GELD MIT RICHTUNG','Deine Finanzen.','Ein klarer Blick auf das, was rein- und rausgeht.')+`<div class="tabs finance-tabs">${['Buchungen','Konten','Schulden','Unterwegs','Plan','Statistik'].map(x=>`<button class="${financeTab===x?'active':''}" data-fin="${x}">${x}</button>`).join('')}</div>`+(financeTab==='Konten'?headerRow('Konten','+ Konto','new-account')+'<button class="quick secondary wide" data-action="transfer-money">Abheben, einzahlen oder zwischen Konten umbuchen ↔</button>'+accountCards()+'<p class="hint">Tippe auf ein Konto, um den aktuellen Stand anzupassen. Buchungen werden automatisch berücksichtigt.</p>':financeTab==='Schulden'?debts():financeTab==='Unterwegs'?outingTools.summary():financeTab==='Plan'?insightTools.shortcuts()+extra.planning():financeTab==='Statistik'?insightTools.shortcuts()+extra.stats():`<div class="grid2"><button class="quick" data-action="income">${icon('plus')}Einnahme</button><button class="quick secondary" data-action="expense">${icon('minus')}Ausgabe</button></div><div class="section-head"><h2>Verlauf</h2><span class="hint">${state.transactions.length} Buchungen</span></div>${insightTools.search()}</div><p class="swipe-hint">Buchung nach links wischen für Details</p>`)}
function debts(){
  const active=state.debts.filter(d=>!d.archived),owed=active.filter(d=>d.direction==='owe').reduce((n,d)=>n+remaining(state,d),0),receivable=active.filter(d=>d.direction==='owed').reduce((n,d)=>n+remaining(state,d),0);
  const rows=state.debts.filter(d=>Boolean(d.archived)===debtArchive&&(debtKind==='Alle'||d.kind===(debtKind==='Privat'?'person':'company'))),archiveCount=state.debts.filter(d=>d.archived).length;
  return `<div class="grid2"><div class="card account"><span class="label">Ich schulde</span><strong>${eur(owed)}</strong></div><div class="card account"><span class="label">Ich bekomme</span><strong>${eur(receivable)}</strong></div></div>`+headerRow(debtArchive?'Bezahlte Einträge':'Verbindlichkeiten',debtArchive?'Aktive ansehen':'+ Hinzufügen',debtArchive?'debt-active':'new-debt')+`<button class="tiny wide" data-debt-archive-toggle>${debtArchive?'← Zurück zu offenen Schulden':'Archiv ansehen ('+archiveCount+')'}</button><div class="tabs">${['Alle','Privat','Unternehmen'].map(k=>`<button data-kind="${k}" class="${debtKind===k?'active':''}">${k}</button>`).join('')}</div>`+(rows.map(d=>{const rest=remaining(state,d);return `<div class="card"><div class="debt-top"><div><h3>${esc(d.name)}</h3><span class="hint">${d.kind==='person'?'Privatperson':'Unternehmen'} · ${d.direction==='owe'?'Ich schulde':'Ich bekomme'}</span></div><strong>${eur(rest)}</strong></div><div class="progress"><span style="width:${(d.amount-rest)/d.amount*100}%"></span></div><div class="debt-meta"><span>${eur(d.amount-rest)} von ${eur(d.amount)} erledigt</span><span>${d.due?`Fällig ${dateLabel(d.due)}`:'Ohne Frist'}</span></div><div class="debt-actions">${d.archived?`<span class="pill">Archiviert ✓</span><button class="tiny" data-debt-restore="${d.id}">Wiederherstellen</button>`:rest?`<button class="tiny" data-pay="${d.id}">Zahlung erfassen →</button><button class="tiny" data-debt-increase="${d.id}">Betrag erhöhen</button>`:`<span class="pill">Vollständig bezahlt ✓</span><button class="tiny" data-debt-increase="${d.id}">Betrag erhöhen</button><button class="tiny" data-debt-archive="${d.id}">Archivieren</button>`}<button class="tiny" data-debt-detail="${d.id}">Details</button></div></div>`}).join('')||`<div class="card"><p class="empty">${debtArchive?'Noch keine bezahlten Schulden im Archiv.':'Keine Einträge in dieser Gruppe.<br>Erfasse, was du schuldest oder zurückbekommst.'}</p></div>`);
}
function goalRows(gs){return goalTools.goalRows(gs);}
function goals(){return goalTools.goals();}
function focus(){return goalTools.focus();}
function work(){return workTools.render();}
function render(){const tabs=[['home','home','Überblick'],['finances','wallet','Finanzen'],['goals','target','Ziele'],['focus','spark','Fokus'],['work','wallet','Arbeit']];$('#main').innerHTML=({home,finances,goals,focus,work}[page])();$('#nav').innerHTML=tabs.map(([p,i,n])=>`<button data-page="${p}" class="${page===p?'active':''}" ${page===p?'aria-current="page"':''}>${icon(i)}${n}</button>`).join('');}
function openSheet(html,onSubmit){$('#sheet').innerHTML=html;$('#modal').showModal();$('#modal').scrollTop=0;const form=$('#sheet form');if(form)form.onsubmit=e=>{e.preventDefault();try{onSubmit(new FormData(form));}catch(err){$('#form-error').textContent=err.message;}};}
function form(title,body,label='Speichern'){return `<h1 style="font-size:26px">${title}</h1><form>${body}<p id="form-error" class="error" role="alert"></p><button class="primary" type="submit">${label}</button></form>`}
const input=(name,label,value='',type='text',extra='')=>`<label for="${name}">${label}</label><input id="${name}" name="${name}" type="${type}" value="${esc(value)}" ${extra}>`;
const select=(name,label,opts,value)=>`<label for="${name}">${label}</label><select name="${name}" id="${name}">${opts.map(([v,l])=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(l)}</option>`).join('')}</select>`;
function transaction(type,debt){const d=debt&&state.debts.find(d=>d.id===debt);if(d)type=d.direction==='owe'?'expense':'income';openSheet(form(d?'Zahlung erfassen':type==='income'?'Einnahme erfassen':'Ausgabe erfassen',input('amount','Betrag in €',d?(remaining(state,d)/100).toFixed(2).replace('.',','):'','text','class="big" inputmode="decimal" placeholder="0,00" required')+select('account','Konto',state.accounts.map(a=>[a.id,a.name]),'cash')+input('date','Datum',today(),'date','required')+select('category','Kategorie',(d?['Schuldenzahlung']:type==='income'?['Bargeld','Gehalt','Verkauf','Geschenk','Sonstiges']:['Lebensmittel','Wohnen','Mobilität','Freizeit','Gesundheit','Sonstiges'] ).concat(state.smart.categories.filter(x=>!x.archived).map(x=>x.name)).filter((x,i,a)=>a.indexOf(x)===i).map(x=>[x,x]))+input('note','Notiz',d?d.name:'','text','maxlength="160" placeholder="Wofür war das?"')+(d?'<p class="hint">Die Zahlung aktualisiert dein Konto und den offenen Schuldenbetrag gemeinsam.</p>':'')),f=>{if(f.get('date')>today())throw Error('Bitte keine zukünftige Buchung erfassen.');const t={type,amount:calculator(f.get('amount')),account:f.get('account'),date:f.get('date'),category:f.get('category'),note:f.get('note').trim(),...(d?{debt:d.id}:{})};if(commit(()=>addTransaction(state,t),'Buchung gespeichert'))$('#modal').close();});}
function accountForm(id){const a=id&&state.accounts.find(a=>a.id===id);openSheet(form(a?'Konto anpassen':'Neues Konto',input('name','Kontoname',a?.name||'','text','required maxlength="60" placeholder="Sparkasse, Revolut, Bargeld zu Hause …"')+select('account-kind','Geldquelle',[['bank','Bankkonto / Karte'],['cash','Bargeld']],a?.kind||'bank')+input('amount','Aktueller Kontostand in €',a?(balance(state,a.id)/100).toFixed(2).replace('.',','):'0,00','text','inputmode="decimal" required')+'<p class="hint">Du kannst beliebig viele Konten und Bargeldquellen anlegen. Für eine Abhebung oder eigene Überweisung nutze „Umbuchen“. Eine Standkorrektur zählt nicht als Einnahme.</p>'),f=>{const amount=cents(f.get('amount')),name=f.get('name').trim(),kind=f.get('account-kind');if(!name)throw Error('Bitte einen Namen eingeben.');if(a&&kind!==a.kind&&state.outings.some(o=>o.status==='open'&&o.lines.some(l=>l.account===id)))throw Error('Die Geldquelle kann erst nach der offenen Unterwegs-Abrechnung geändert werden.');if(commit(()=>{if(a){const current=state.accounts.find(x=>x.id===id);current.opening+=amount-balance(state,id);current.name=name;current.kind=kind;}else state.accounts.push({id:uid(),name,kind,opening:amount});},'Konto gespeichert'))$('#modal').close();});}
function debtForm(){openSheet(form('Schuld erfassen',input('name','Person oder Unternehmen','','text','required maxlength="100"')+select('kind','Gruppe',[['person','Privatperson'],['company','Unternehmen']],'person')+select('direction','Richtung',[['owe','Ich schulde Geld'],['owed','Ich bekomme Geld']],'owe')+input('amount','Offener Betrag in €','','text','required inputmode="decimal" placeholder="0,00"')+input('due','Fällig am · optional','','date')+`<div id="loan-funding" class="funding-box"><label class="funding-check"><input type="checkbox" name="receive-loan" id="receive-loan"><span>Geliehenes Geld auch meinem Guthaben gutschreiben</span></label><div id="loan-fields" hidden>${select('loan-account','Geld erhalten auf',state.accounts.map(a=>[a.id,a.name]),'cash')}${input('loan-date','Erhalten am',today(),'date',`max="${today()}"`)}<p class="hint">Der volle Betrag erhöht dieses Konto. Die Schuld bleibt offen. Der Eingang zählt nicht als verdiente Einnahme.</p></div></div>`+'<p class="hint">Haken nur setzen, wenn der Geldeingang noch nicht im Kontostand oder als Buchung enthalten ist.</p>'),f=>{const amount=cents(f.get('amount')),name=f.get('name').trim(),funding=f.has('receive-loan')?{account:f.get('loan-account'),date:f.get('loan-date')}:null;if(funding&&funding.date>today())throw Error('Bitte ein Datum bis heute wählen.');if(commit(()=>createDebt(state,{name,amount,kind:f.get('kind'),direction:f.get('direction'),due:f.get('due')},funding),funding?'Schuld und Geldeingang gespeichert':'Schuld gespeichert'))$('#modal').close();});}
function increaseDebtForm(id){
  const d=state.debts.find(d=>d.id===id);if(!d||d.archived)return;
  const canReceive=d.kind==='person'&&d.direction==='owe';
  const funding=canReceive?`<div class="funding-box"><label class="funding-check"><input type="checkbox" name="receive-more-loan" id="receive-more-loan"><span>Zusätzlichen Betrag auch meinem Guthaben gutschreiben</span></label><div id="more-loan-fields" hidden>${select('more-loan-account','Geld erhalten auf',state.accounts.map(a=>[a.id,a.name]),'cash')}${input('more-loan-date','Erhalten am',today(),'date',`max="${today()}"`)}<p class="hint">Nur auswählen, wenn das zusätzliche Geld wirklich auf diesem Konto oder bar eingegangen ist.</p></div></div>`:'';
  openSheet(form('Betrag erhöhen',`<p class="subtitle">${esc(d.name)} · bisher insgesamt ${eur(d.amount)}</p>`+input('increase-amount','Zusätzlicher Betrag in €','','text','required inputmode="decimal" placeholder="0,00"')+funding+'<p class="hint">Der Zusatzbetrag wird zur bestehenden Schuld oder Forderung addiert. Bereits erfasste Zahlungen bleiben erhalten.</p>'),f=>{const amount=cents(f.get('increase-amount')),received=f.has('receive-more-loan')?{account:f.get('more-loan-account'),date:f.get('more-loan-date')}:null;if(received&&received.date>today())throw Error('Bitte ein Datum bis heute wählen.');if(commit(()=>increaseDebt(state,id,amount,received),received?'Schuldenbetrag und Geldeingang erhöht':'Schuldenbetrag erhöht'))$('#modal').close();});
}
function goalForm(id){return goalTools.goalForm(id);}
function toggleGoal(id){return goalTools.toggleGoal(id);}
function ritual(d=today()){const j=state.journals[d]||{};const fields=[['wish','Dein Wunsch','Was ist dir wichtig und machbar?'],['outcome','Das beste Ergebnis','Wie würde sich das anfühlen?'],['obstacle','Dein inneres Hindernis','Was hält dich möglicherweise zurück?'],['plan','Dein Wenn-dann-Plan','Wenn … passiert, dann werde ich …'],['belief','Ein hinderlicher Glaubenssatz','Welcher Gedanke steht dir im Weg?'],['evidence','Deine Erfahrung','Was spricht dafür, was spricht dagegen?'],['reframe','Dein neuer Satz','Eine realistische, freundliche Alternative.']];openSheet(form(`Dein Check-in · ${dateLabel(d)}`,`<p class="hint">Nimm dir einen ruhigen Moment. Formuliere deinen Wunsch und eine Handlung, die in deiner Kontrolle liegt.</p>`+fields.map(([n,l,p],i)=>`<div class="step-label"><span>${i+1}</span><label for="${n}">${l}</label></div><textarea style="margin-top:9px" id="${n}" name="${n}" maxlength="2000" placeholder="${p}">${esc(j[n]||'')}</textarea>`).join('')+select('done','Status',[['false','Als Entwurf speichern'],['true','Für diesen Tag abschließen']],String(j.done||false))),f=>{const next=Object.fromEntries(fields.map(([n])=>[n,f.get(n).trim()]));next.done=f.get('done')==='true';if(next.done&&(!next.wish||!next.obstacle||!next.plan))throw Error('Zum Abschließen bitte Wunsch, Hindernis und Plan ausfüllen.');if(commit(()=>state.journals[d]=next,'Check-in gespeichert'))$('#modal').close();});}
function txDetail(id){const t=state.transactions.find(t=>t.id===id);if(!t)return;const outing=state.outings.find(o=>o.id===t.outing||o.status==='closed'&&o.lines.some(l=>l.recordedIds.includes(id)));openSheet(`<h1 style="font-size:26px">${esc(t.note||t.category)}</h1><p class="subtitle">${dateLabel(t.date)} · ${esc(t.category)}</p><h2>${t.type==='income'?'+':'−'}${eur(t.amount)}</h2>${!t.debt&&!t.schedule&&!t.transfer&&!t.loanFunding&&!t.outing?`<div class="grid2"><button class="quick secondary" data-smart-tx="${id}">Bearbeiten</button><button class="quick secondary" data-smart-split="${id}">Aufteilen</button></div><button class="tiny wide" data-smart-duplicate="${id}">Als Vorlage erneut buchen</button>`:''}${outing?`<p class="hint">Diese Buchung gehört zu „${esc(outing.name)}“. Korrigiere sie über die Abrechnung.</p><button class="primary" data-outing="${outing.id}">Abrechnung öffnen</button>`:`<p class="hint">${t.transfer?'Beim Löschen werden beide Seiten der Umbuchung gemeinsam zurückgerechnet.':t.loanFunding?'Der Geldeingang wird zurückgenommen; die Schuld bleibt offen.':'Beim Löschen wird der Kontostand'+(t.debt?' und die offene Schuld':'')+' zurückgerechnet.'}</p>${t.schedule?'<p class="hint">Der zugehörige geplante Termin wird wieder offen.</p>':''}<button class="primary" data-delete-tx="${id}">${t.transfer?'Umbuchung vollständig löschen':'Buchung löschen'}</button>`}`);}
function debtDetail(id){
  const d=state.debts.find(d=>d.id===id),ts=state.transactions.filter(t=>t.debt===id||t.loanFunding===id),rest=remaining(state,d);
  const controls=d.archived?`<button class="primary" data-debt-restore="${id}">Aus Archiv wiederherstellen</button>`:`<button class="quick secondary wide" data-debt-increase="${id}">Betrag erhöhen</button>${rest===0?`<button class="primary" data-debt-archive="${id}">Als bezahlt archivieren</button>`:''}`;
  openSheet(`<h1 style="font-size:26px">${esc(d.name)}</h1><p class="subtitle">Noch offen: ${eur(rest)} · Gesamtbetrag: ${eur(d.amount)}</p><div class="card">${ts.length?txRows(ts):'<p class="empty">Noch keine Zahlungen erfasst.</p>'}</div>${controls}<button class="quick secondary wide" data-smart-debt="${id}">Verlauf, Zielrate und Simulation</button>${ts.length?'<p class="hint">Geliehenes Geld erhöht dein Guthaben, reduziert aber keine Schuld. Gelöschte Schuldenzahlungen öffnen einen archivierten Eintrag automatisch wieder.</p>':`<button class="quick secondary wide" data-delete-debt="${id}">Schuld löschen</button>`}`);
}
function settings(){openSheet(`<h1 style="font-size:26px">Dein Hany.</h1><p class="subtitle">Version 1.0 · Deine persönliche Web-App</p><div class="card"><h3>Dein persönlicher Überblick</h3><p class="hint">Finanzen, Ziele und Glaubenssätze bleiben auf diesem Gerät. Sichere sie regelmäßig, besonders vor einem Gerätewechsel oder einer Deinstallation.</p></div>${loadError?'<p class="error">Gespeicherte Daten konnten nicht gelesen werden. Exportiere die Originaldaten vor einer Wiederherstellung.</p>':''}<div class="settings-actions"><button class="quick secondary" data-action="smart-hub">Smarter Alltag, Regeln & Suche</button><button class="primary" data-action="backup">${loadError?'Originaldaten sichern':'Verschlüsselte Sicherung erstellen'}</button><button class="quick secondary" data-action="restore">Sicherung wiederherstellen</button><button class="quick secondary" data-action="csv-import">Bankumsätze aus CSV importieren</button><button class="quick secondary" data-action="reminders">Erinnerungen & Kalender</button><button class="quick secondary" data-action="outings">Unterwegs abrechnen</button><button class="quick secondary" data-action="budgets">Monatliche Budgets</button><button class="quick secondary" data-action="forecast">30-Tage-Geldvorschau</button><button class="quick secondary" data-action="install-help">Installation & Aktualisierung</button></div><p class="hint">CSV-Dateien werden lokal verarbeitet. Eine direkte Verbindung zu echten Bankkonten ist noch nicht eingerichtet. Verschlüsselt wird die Sicherungsdatei; der lokale App-Speicher hat keine zusätzliche App-Sperre.</p>`);}
function backup(){if(!loadError)return dataTools.backup();const raw=loadError?localStorage.getItem(KEY):JSON.stringify(state,null,2);openSheet(`<h1 style="font-size:26px">Deine Datensicherung</h1><p class="hint">Kopiere den vollständigen Text und speichere ihn sicher, zum Beispiel in einer eigenen Datei. Die Sicherung enthält deine persönlichen Finanzdaten.</p><textarea id="backup-text" readonly style="height:250px;font-size:12px">${esc(raw)}</textarea><button class="primary" data-action="copy-backup">Text kopieren / auswählen</button>`);}
function restore(){return dataTools.restore();}
const extra=financeUI({paymentTools:(id,due)=>smartTools.paymentTools(id,due),state:()=>state,esc,eur,icon,input,select,form,openSheet,headerRow,txRows,commit,render,toast,removeEntry});
const workTools=workUI({state:()=>state,esc,eur,input,select,form,openSheet,commit,toast});
const rituals=ritualsUI({state:()=>state,esc,eur,input,select,form,openSheet,commit,toast});
const context={ritualCards:()=>rituals.cards(),ritualHistory:p=>rituals.history(p),smartCheckin:date=>smartTools.checkin(date),goalMoney:g=>smartTools.goalMoney(g),state:()=>state,esc,eur,icon,input,select,form,openSheet,commit,render,toast,txRows,uid,migrate,addTransaction};
const goalTools=goalsUI(context),dataTools=dataToolsUI({...context,restoreState:imported=>{const oldError=loadError;loadError=false;const ok=commit(()=>state=imported,'Sicherung wiederhergestellt');if(!ok)loadError=oldError;return ok;}}),reminderTools=remindersUI(context),insightTools=insightsUI(context),outingTools=outingsUI(context);
const smartTools=smartUI({...context,goalDetail:id=>goalTools.goalDetail(id),planDetail:(id,due)=>extra.detail(id,due)});
const pwa=initPwa({openSheet,toast});
const actions={...rituals.actions,...smartTools.actions,...extra.actions,...goalTools.actions,...dataTools.actions,...reminderTools.actions,...insightTools.actions,...outingTools.actions,...smartTools.actions,'install-help':()=>pwa.help(),statistics:()=>{financeTab='Statistik';go('finances')},planning:()=>{financeTab='Plan';go('finances')},income:()=>transaction('income'),expense:()=>transaction('expense'),accounts:()=>{financeTab='Konten';go('finances')},transactions:()=>{financeTab='Buchungen';go('finances')},goals:()=>go('goals'),focus:()=>go('focus'),'new-account':()=>accountForm(),'new-debt':debtForm,'new-goal':()=>goalForm(),'toggle-completed':()=>{showDone=!showDone;render()},ritual:()=>ritual(),backup,restore,'copy-backup':async()=>{const el=$('#backup-text');el.focus();el.select();el.setSelectionRange(0,el.value.length);try{await navigator.clipboard.writeText(el.value);toast('Sicherung kopiert')}catch{toast('Text ausgewählt. Über das Auswahlmenü kopieren.')}}};
actions['debt-active']=()=>{debtArchive=false;render()};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.debtArchiveToggle!==undefined){debtArchive=!debtArchive;render()}if(d.debtIncrease){if(document.querySelector('#modal').open)document.querySelector('#modal').close();increaseDebtForm(d.debtIncrease)}if(d.debtArchive&&commit(()=>setDebtArchived(state,d.debtArchive,true),'Als bezahlt archiviert')&&$('#modal').open)$('#modal').close();if(d.debtRestore&&commit(()=>setDebtArchived(state,d.debtRestore,false),'Aus Archiv wiederhergestellt')&&$('#modal').open)$('#modal').close();});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(dataTools.click(d))return;workTools.click(d);rituals.click(d);smartTools.click(d);goalTools.click(d);outingTools.click(d);insightTools.click(d);extra.click(d);if(d.action)actions[d.action]?.();if(d.page)go(d.page);if(d.fin){financeTab=d.fin;render()}if(d.horizon){horizon=d.horizon;showDone=false;render()}if(d.kind){debtKind=d.kind;render()}if(d.account)accountForm(d.account);if(d.toggle)toggleGoal(d.toggle);if(d.goalDetail)goalTools.goalDetail(d.goalDetail);if(d.pay)transaction('',d.pay);if(d.journal)ritual(d.journal);if(d.txDetail){if($('#modal').open)$('#modal').close();txDetail(d.txDetail)}if(d.debtDetail)debtDetail(d.debtDetail);if(d.deleteTx){removeEntry('transactions',d.deleteTx);$('#modal').close()}if(d.deleteGoal){removeEntry('goals',d.deleteGoal);$('#modal').close()}if(d.deleteDebt){removeEntry('debts',d.deleteDebt);$('#modal').close()}});
document.addEventListener('change',e=>{if(['kind','direction','receive-loan'].includes(e.target.id)&&$('#loan-funding')){const eligible=$('#kind').value==='person'&&$('#direction').value==='owe';$('#loan-funding').hidden=!eligible;if(!eligible)$('#receive-loan').checked=false;$('#loan-fields').hidden=!$('#receive-loan').checked;}extra.change(e);goalTools.change(e);dataTools.change(e);insightTools.change(e);});
document.addEventListener('change',e=>{if(e.target.id==='receive-more-loan'&&$('#more-loan-fields'))$('#more-loan-fields').hidden=!e.target.checked;});
document.addEventListener('input',e=>{insightTools.input(e);smartTools.input(e);workTools.input(e)});
$('#close').onclick=()=>$('#modal').close();$('#settings').onclick=settings;$('.brand').onclick=e=>{e.preventDefault();go('home')};$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=$('#modal').getBoundingClientRect();if(e.clientY<r.top||e.clientX<r.left||e.clientX>r.right)$('#modal').close();}});
let touch;$('#main').addEventListener('touchstart',e=>{if(e.touches.length!==1)return;touch={x:e.touches[0].clientX,y:e.touches[0].clientY,target:e.target};},{passive:true});$('#main').addEventListener('touchend',e=>{if(!touch)return;const dx=e.changedTouches[0].clientX-touch.x,dy=e.changedTouches[0].clientY-touch.y,t=touch.target;touch=null;if(Math.abs(dx)<85||Math.abs(dy)>45||t.closest('input,textarea,select,.tabs'))return;const goal=t.closest('[data-goal]'),tx=t.closest('[data-tx]');if(goal&&dx>0){const g=state.goals.find(g=>g.id===goal.dataset.goal);if(!g.done)toggleGoal(g.id);}else if(tx&&dx<0)txDetail(tx.dataset.tx);else if(!goal&&!tx){const pages=['home','finances','goals','focus','work'];const next=pages.indexOf(page)+(dx<0?1:-1);if(pages[next])go(pages[next]);}},{passive:true});
$('#main').addEventListener('contextmenu',e=>{const tx=e.target.closest('[data-tx]'),goal=e.target.closest('[data-goal]');if(tx||goal){e.preventDefault();if(tx)txDetail(tx.dataset.tx);else goalTools.goalDetail(goal.dataset.goal);}});
render();if(loadError)toast('Daten konnten nicht geladen werden. Bitte Einstellungen öffnen.');

let renderedDay=today();document.addEventListener('visibilitychange',()=>{if(!document.hidden&&renderedDay!==today()&&!$('#modal').open){renderedDay=today();render();}});
const workClock=setInterval(()=>{if(page==='work'&&currentShift(state)&&!$('#modal').open)render();},30000);workClock.unref?.();
