import {today,cents} from './model.js';
import {budgetSummary,forecast,searchTransactions} from './insights.js';

export function insightsUI(c){
  const {esc,eur,input,select,form,openSheet}=c;
  let query='',account='all',forecastAccount='all',searchLimit=100;
  const state=()=>c.state(),close=()=>document.querySelector('#modal').close();
  const accounts=()=>[['all','Alle Konten'],...state().accounts.map(a=>[a.id,a.name])];
  const monthLabel=()=>new Date(today()+'T12:00:00').toLocaleDateString('de-DE',{month:'long',year:'numeric'});
  const dayLabel=d=>new Date(d+'T12:00:00').toLocaleDateString('de-DE',{day:'numeric',month:'short',weekday:'short'});
  function shortcuts(){return '<div class="insight-shortcuts"><button class="quick secondary" data-action="budgets">Monatsbudgets ↗</button><button class="quick secondary" data-action="forecast">30-Tage-Vorschau ↗</button></div>';}
  function searchResults(){const tx=searchTransactions(state(),query,account);return `<p class="hint" role="status">${tx.length} passende Buchungen</p><div class="card">${tx.length?c.txRows(tx.slice(0,searchLimit)):'<p class="empty">Keine passenden Buchungen.<br>Ändere die Suche oder das Konto.</p>'}</div>${tx.length>searchLimit?'<button class="quick secondary wide" data-action="search-more">Weitere Buchungen anzeigen</button>':''}`;}
  function search(){return `<div class="transaction-search">${input('tx-search','Buchungen durchsuchen',query,'search','placeholder="Notiz, Kategorie, Datum oder Betrag" autocomplete="off"')}${select('tx-search-account','Konto filtern',accounts(),account)}<div id="tx-search-results">${searchResults()}</div>`;}
  function redrawSearch(){const el=document.querySelector('#tx-search-results');if(el)el.innerHTML=searchResults();}
  function budgets(){const rows=budgetSummary(state(),today().slice(0,7));openSheet(`<h1 class="sheet-title">Deine Monatsbudgets</h1><p class="subtitle">${monthLabel()} · Tatsächlich gebuchte Ausgaben</p><button class="primary" data-action="new-budget">Budget anlegen</button>${rows.map(b=>`<div class="card budget-card"><div class="section-head"><h2>${esc(b.category)}</h2><button class="tiny" data-budget-edit="${b.id}">Bearbeiten</button></div><strong class="budget-value ${b.left<0?'negative':''}">${eur(Math.abs(b.left))} ${b.left<0?'über Budget':'übrig'}</strong><div class="progress"><span class="${b.left<0?'budget-over':''}" style="width:${Math.min(100,b.percent)}%"></span></div><p class="hint">${eur(b.spent)} von ${eur(b.amount)} · ${b.percent}% genutzt</p><button class="tiny" data-budget-detail="${b.id}">Ausgaben ansehen →</button></div>`).join('')||'<div class="card"><p class="empty">Wie viel möchtest du für Lebensmittel, Freizeit oder Wohnen ausgeben?</p></div>'}<p class="hint">Die Limits gelten jeden Monat erneut für alle Konten. Frühere Buchungen bleiben erhalten. Geplante Zahlungen zählen erst, wenn du sie als bezahlt erfasst. Nicht genutztes Budget wird nicht übertragen.</p>`);}
  function budgetForm(id){const b=state().budgets.find(b=>b.id===id);const categories=[...new Set(['Lebensmittel','Wohnen','Mobilität','Freizeit','Gesundheit','Sonstiges',...state().transactions.filter(t=>t.type==='expense').map(t=>t.category),...state().schedules.filter(s=>s.type==='expense').map(s=>s.category)])];openSheet(form(b?'Budget bearbeiten':'Monatliches Budget',input('budget-category','Kategorie',b?.category||'','text','required maxlength="100" list="budget-categories"')+`<datalist id="budget-categories">${categories.map(x=>`<option value="${esc(x)}"></option>`).join('')}</datalist>`+input('budget-amount','Limit pro Monat in €',b?(b.amount/100).toFixed(2).replace('.',','):'','text','required inputmode="decimal" placeholder="300,00"')+(b?`<button class="tiny danger" type="button" data-budget-delete="${b.id}">Budget entfernen</button>`:'')),f=>{const category=f.get('budget-category').trim(),amount=cents(f.get('budget-amount'));if(!category||amount<=0)throw Error('Bitte Kategorie und ein positives Limit eingeben.');if(state().budgets.some(x=>x.id!==id&&x.category.toLocaleLowerCase('de-DE')===category.toLocaleLowerCase('de-DE')))throw Error('Für diese Kategorie gibt es bereits ein Budget.');if(c.commit(()=>{if(b)Object.assign(state().budgets.find(x=>x.id===id),{category,amount});else state().budgets.push({id:c.uid(),category,amount});},'Budget gespeichert'))budgets();});}
  function budgetDetail(id){const b=budgetSummary(state(),today().slice(0,7)).find(b=>b.id===id);if(!b)return;openSheet(`<h1 class="sheet-title">${esc(b.category)}</h1><p class="subtitle">${monthLabel()} · ${eur(b.spent)} ausgegeben</p><div class="card">${b.tx.length?c.txRows(b.tx):'<p class="empty">Noch keine Ausgaben in dieser Kategorie.</p>'}</div><button class="quick secondary wide" data-action="budgets">Zurück zu Budgets</button>`);}
  function showForecast(){const f=forecast(state(),today(),30,forecastAccount);openSheet(`<h1 class="sheet-title">Die nächsten 30 Tage</h1><p class="subtitle">Was deine eingetragenen Zahlungspläne für deinen Kontostand bedeuten.</p>${select('forecast-account','Konto',accounts(),forecastAccount)}<div class="grid2 forecast-summary"><div class="card"><span class="label">Heute gebucht</span><strong>${eur(f.opening)}</strong></div><div class="card"><span class="label">Voraussichtlich am Ende</span><strong class="${f.closing<0?'negative':''}">${eur(f.closing)}</strong></div></div><div class="forecast-low ${f.lowest<0?'forecast-warning':''}">Niedrigster Stand einschließlich heute: <strong>${eur(f.lowest)}</strong></div><p class="hint">Berechnung aus dem aktuellen Stand und offenen Zahlungsplänen inklusive eingetragener Gebühren. ${f.overdue?`${f.overdue} überfällige Termine werden heute angenommen. `:''}Erwartete Eingänge sind ungewiss. Nicht geplante Ausgaben und separat erfasste Schulden fehlen. Tagesstände gelten nach allen Zahlungen des Tages.</p><div class="card">${f.rows.map(r=>`<button class="forecast-row" data-forecast-day="${r.date}"><span><strong>${dayLabel(r.date)}</strong><small>${r.items.length?`${r.items.length} Termine · +${eur(r.income)} / −${eur(r.expense)}`:'Keine geplanten Zahlungen'}</small></span><strong class="${r.balance<0?'negative':''}">${eur(r.balance)}</strong></button>`).join('')}</div>`);}
  function forecastDay(date){const row=forecast(state(),today(),30,forecastAccount).rows.find(r=>r.date===date);if(!row)return;openSheet(`<h1 class="sheet-title">${dayLabel(date)}</h1><p class="subtitle">Voraussichtlicher Tagesstand: ${eur(row.balance)}</p><div class="card">${row.items.map(o=>`<button class="forecast-row" data-plan-detail="${o.schedule}" data-due="${o.due}"><span><strong>${esc(o.name)}</strong><small>Fällig ${dayLabel(o.due)}${o.due<today()?' · überfällig':''}</small></span><strong>${o.type==='income'?'+':'−'}${eur(o.amount)}</strong></button>`).join('')||'<p class="empty">Keine geplanten Zahlungen an diesem Tag.</p>'}</div><button class="quick secondary wide" data-action="forecast">Zurück zur Vorschau</button>`);}
  return {shortcuts,search,actions:{budgets,'new-budget':()=>budgetForm(),forecast:showForecast,'search-more':()=>{searchLimit+=100;redrawSearch();}},click(d){if(d.budgetEdit)budgetForm(d.budgetEdit);if(d.budgetDetail)budgetDetail(d.budgetDetail);if(d.budgetDelete){const snapshot=structuredClone(state().budgets);if(c.commit(()=>state().budgets=state().budgets.filter(b=>b.id!==d.budgetDelete))){budgets();c.toast('Budget entfernt',()=>c.commit(()=>state().budgets=snapshot,'Budget wiederhergestellt'));}}if(d.forecastDay)forecastDay(d.forecastDay);},change(e){if(e.target.id==='tx-search-account'){account=e.target.value;searchLimit=100;redrawSearch();}if(e.target.id==='forecast-account'){forecastAccount=e.target.value;showForecast();}},input(e){if(e.target.id==='tx-search'){query=e.target.value;searchLimit=100;redrawSearch();}}};
}
