import {validateMoneyFlows} from './money-flows.js';
import {isOccurrence} from './planning.js';
import {migrateGoals, validateGoalsState} from './goals.js';
import {reminderDefaults, validReminderSettings} from './reminders.js';
export const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
export const uid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
export const initial=()=>({version:4,outings:[],beliefs:[],practice:[],reviews:[],budgets:[],reminderSettings:reminderDefaults(),schedules:[],occurrences:[],accounts:[{id:'cash',name:'Bargeld',kind:'cash',opening:0},{id:'bank',name:'Girokonto',kind:'bank',opening:0}],transactions:[],debts:[],goals:[],journals:{}});
export function cents(raw){const s=String(raw).trim().replace(/\s/g,'');if(!/^-?\d+(?:[,.]\d{1,2})?$/.test(s))throw Error('Bitte einen Betrag wie 12,50 eingeben, ohne Tausenderpunkte.');const n=Math.round(Number(s.replace(',','.'))*100);if(!Number.isSafeInteger(n)||Math.abs(n)>1e12)throw Error('Betrag zu groß.');return n;}
export const balance=(s,id)=>s.accounts.find(a=>a.id===id).opening+s.transactions.filter(t=>t.account===id).reduce((n,t)=>n+(t.type==='income'?t.amount:-t.amount),0);
export const remaining=(s,d)=>Math.max(0,d.amount-s.transactions.filter(t=>t.debt===d.id).reduce((n,t)=>n+t.amount,0));
export function addTransaction(s,t){if(!Number.isSafeInteger(t.amount)||t.amount<=0||!s.accounts.some(a=>a.id===t.account)||!['income','expense'].includes(t.type)||!validDate(t.date))throw Error('Betrag, Konto und Datum prüfen.');if(t.debt){const d=s.debts.find(d=>d.id===t.debt);if(!d||t.amount>remaining(s,d)||t.type!==(d.direction==='owe'?'expense':'income'))throw Error('Zahlung passt nicht zur offenen Schuld.');}if(t.schedule){const rule=s.schedules.find(r=>r.id===t.schedule);const override=s.occurrences.find(o=>o.schedule===t.schedule&&o.due===t.due);if(!rule||!isOccurrence(rule,t.due)||t.type!==rule.type||t.debt||s.transactions.some(x=>x.schedule===t.schedule&&x.due===t.due)||override?.skipped||t.amount!==rule.amount+(override?.fee||0))throw Error('Dieser Termin ist bereits erledigt oder der Betrag passt nicht.');}s.transactions.unshift({...t,id:uid()});}
const validDate=v=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&!isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v;
export function validate(s){const fail=()=>{throw Error('Diese Sicherung hat kein gültiges Hany-Format.');};if(!s||s.version!==4||!Array.isArray(s.accounts)||!s.accounts.length||!Array.isArray(s.transactions)||!Array.isArray(s.debts)||!Array.isArray(s.goals)||!s.journals||typeof s.journals!=='object'||Array.isArray(s.journals))fail();const str=v=>typeof v==='string'&&v.length<10000;const int=v=>Number.isSafeInteger(v)&&Math.abs(v)<=1e12;const unique=arr=>new Set(arr.map(x=>x.id)).size===arr.length&&arr.every(x=>typeof x.id==='string'&&/^[A-Za-z0-9_-]{1,100}$/.test(x.id));if(!Array.isArray(s.schedules)||!Array.isArray(s.occurrences)||![s.accounts,s.transactions,s.debts,s.goals,s.schedules].every(unique))fail();s.accounts.forEach(a=>{if(!str(a.name)||!int(a.opening))fail()});s.debts.forEach(d=>{if(!str(d.name)||!int(d.amount)||d.amount<=0||!['owe','owed'].includes(d.direction)||!['person','company'].includes(d.kind)||!(d.due===''||validDate(d.due))||!(d.archived===undefined||typeof d.archived==='boolean'))fail()});s.transactions.forEach(t=>{if(!int(t.amount)||t.amount<=0||!str(t.note)||!str(t.category)||!validDate(t.date)||!['income','expense'].includes(t.type)||!s.accounts.some(a=>a.id===t.account))fail();if(t.debt){const d=s.debts.find(d=>d.id===t.debt);if(!d||t.type!==(d.direction==='owe'?'expense':'income'))fail();}});s.debts.forEach(d=>{const paid=s.transactions.filter(t=>t.debt===d.id).reduce((a,t)=>a+t.amount,0);if(paid>d.amount||d.archived&&paid!==d.amount)fail()});s.goals.forEach(g=>{if(!str(g.title)||!['Tag','Woche','Monat','Jahr','Langzeit'].includes(g.horizon)||typeof g.done!=='boolean'||!(g.due===''||validDate(g.due))||!(g.done?validDate(g.completed):g.completed===''))fail()});validateMoneyFlows(s,fail);validatePlanning(s,fail);validateGoalsState(s,fail);if(!validReminderSettings(s.reminderSettings)||!Array.isArray(s.budgets)||!unique(s.budgets)||new Set(s.budgets.map(b=>b.category)).size!==s.budgets.length)fail();for(const b of s.budgets)if(!str(b.category)||!b.category.trim()||!int(b.amount)||b.amount<=0)fail();Object.entries(s.journals).forEach(([k,j])=>{if(!validDate(k)||!j||!['wish','outcome','obstacle','plan','belief','reframe','evidence'].every(x=>str(j[x]))||typeof j.done!=='boolean')fail()});return s;}

export function migrate(raw) {
  const s=structuredClone(raw);
  if(s?.version===1){s.version=2;s.schedules=[];s.occurrences=[];}
  if(s?.version===2){s.version=3;migrateGoals(s);s.budgets=[];s.reminderSettings=reminderDefaults();}
  if(s?.version===3){s.version=4;s.outings=[];if(Array.isArray(s.accounts))s.accounts=s.accounts.map(a=>({...a,kind:a.id==='cash'?'cash':'bank'}));}
  return validate(s);
}
function validatePlanning(s,fail) {
  const money=v=>Number.isSafeInteger(v)&&v>=0&&v<=1e12;
  const date=v=>validDate(v)&&v>='2000-01-01'&&v<='2100-12-31';
  const text=v=>typeof v==='string'&&v.length<10000;
  for(const r of s.schedules) if(!text(r.name)||!r.name.trim()||!money(r.amount)||r.amount===0||!['income','expense'].includes(r.type)||!s.accounts.some(a=>a.id===r.account)||!text(r.category)||!date(r.start)||!['once','daily','weekly','fortnightly','monthly','quarterly','yearly'].includes(r.cycle)||!(r.end===''||date(r.end)&&r.end>=r.start)||!(r.stoppedOn===''||date(r.stoppedOn)))fail();
  const keys=new Set();for(const o of s.occurrences){const r=s.schedules.find(r=>r.id===o.schedule),key=o.schedule+':'+o.due;if(!r||!isOccurrence(r,o.due)||!date(o.due)||keys.has(key)||!money(o.fee)||(r.type==='income'&&o.fee!==0)||!text(o.note)||typeof o.skipped!=='boolean')fail();keys.add(key);}
  const paid=new Set();for(const t of s.transactions)if(t.schedule){const r=s.schedules.find(r=>r.id===t.schedule),key=t.schedule+':'+t.due;if(!r||!isOccurrence(r,t.due)||!date(t.due)||t.type!==r.type||t.debt||paid.has(key)||s.occurrences.some(o=>o.schedule===t.schedule&&o.due===t.due&&o.skipped))fail();paid.add(key);}
}
