import {today,uid} from './model.js';
import {dailyPractice} from './goals.js';
import {addDays} from './planning.js';
import {dailyAffirmation} from './rituals.js';

export function ritualsUI(c){
 const s=()=>c.state(),{esc,form,select,openSheet}=c;
 const area=(id,title,v='')=>`<label for="${id}">${title}</label><textarea id="${id}" name="${id}" maxlength="2000">${esc(v)}</textarea>`;
 const box=(name,title,checked)=>`<label class="goal-checkbox"><input type="checkbox" name="${name}" ${checked?'checked':''}> ${title}</label>`;
 const save=(fn,msg)=>{if(c.commit(fn,msg))document.querySelector('#modal').close();};
 const current=date=>{const p=s().practice.find(p=>p.date===date),r=p?.ritual||{},a=dailyAffirmation(date);return {p,r,a:{...a,text:r.affirmationText??a.text}};};
 function cards(date=today()){const {p,r,a}=current(date);return `<div class="card"><span class="pill">DEIN TAGESIMPULS · ${esc(a.topic)}</span><h2>„${esc(a.text)}“</h2><p class="hint">Langsam lesen. Prüfe, ob der Satz zu dir passt, und verbinde ihn mit einer Handlung.</p><button class="quick secondary wide" data-ritual="impulse" data-date="${date}">${r.affirmationAdopted?'Bewusst übernommen ✓':r.affirmationRead?'Gelesen · für mich prüfen':'Lesen & für mich übernehmen'}</button></div><div class="grid2"><button class="card smart-start" data-ritual="morning" data-date="${date}"><span class="pill">MORGEN · 3 MINUTEN</span><h3>Dankbar starten.<br>Einen Schritt wählen.</h3><small>${r.morningDone?'Gespeichert ✓':'Dankbarkeit · Ziel · Hindernis · Plan'} ›</small></button><button class="card smart-start" data-ritual="evening" data-date="${date}"><span class="pill">ABEND · 3 MINUTEN</span><h3>Erreichtes sehen.<br>Morgen vorbereiten.</h3><small>${r.eveningDone?'Gespeichert ✓':'Erfahrung · Dankbarkeit · nächster Tag'} ›</small></button></div>${p?.action?`<div class="card"><h3>Mein heutiger Schritt</h3><p>${esc(p.action)}</p>${r.trigger?`<small>${esc(r.trigger)}</small>`:''}</div>`:''}`;}
 function impulse(date){const {r,a}=current(date);openSheet(form('Dein Satz für heute',`<span class="pill">${esc(a.topic)} · ${date}</span>`+area('affirmationText','Passe den Satz an, wenn das für dich stimmiger ist',a.text)+box('affirmationRead','Ich habe den Satz bewusst gelesen.',r.affirmationRead)+box('affirmationAdopted','Dieser Satz passt zu mir. Ich möchte ihn heute als Erinnerung nutzen.',r.affirmationAdopted)+box('saveBelief','Zusätzlich als persönlichen Glaubenssatz speichern.',false)+'<p class="hint">Übernehmen ist freiwillig. Lesen und Handeln bleiben getrennt. Der Satz ist eine Anregung, kein Versprechen.</p>'),f=>{const text=f.get('affirmationText').trim();if(!text)throw Error('Bitte einen Satz eintragen.');if(f.has('affirmationAdopted')&&!f.has('affirmationRead'))throw Error('Bitte zuerst das bewusste Lesen bestätigen.');save(()=>{const p=dailyPractice(s(),date);p.ritual={...p.ritual,affirmationId:a.id,affirmationText:text,affirmationRead:f.has('affirmationRead'),affirmationAdopted:f.has('affirmationAdopted')};if(f.has('saveBelief')&&!s().beliefs.some(b=>b.text===text&&!b.archived))s().beliefs.push({id:uid(),text,oldThought:'',evidence:'',goalId:'',archived:false,created:today()});},'Tagesimpuls gespeichert');});}
 function morning(date){const {p,r}=current(date),g=s().goals.find(g=>!g.done&&g.nextAction);openSheet(form('Deine Morgenroutine',`<p class="subtitle">${date} · Du musst nicht alle Felder ausfüllen.</p>`+area('gratitudeMorning','1 · Wofür bin ich gerade dankbar? Was genau hat mir geholfen?',r.gratitudeMorning)+select('goalId','2 · Welches Ziel ist heute wichtig?',[['','Mein Alltag allgemein'],...s().goals.map(g=>[g.id,g.title])],p?.goalId||'')+area('intention','Warum ist mir das wichtig? Wie soll ein guter Schritt aussehen?',r.intention)+area('action','3 · Meine eine konkrete Handlung heute',p?.action||g?.nextAction||'')+area('obstacle','4 · Was könnte mich daran hindern?',r.obstacle)+area('trigger','5 · Mein Wenn-dann-Plan: Wann starte ich? Wie gehe ich mit dem Hindernis um?',r.trigger)+box('complete','Meine Morgenroutine ist für heute abgeschlossen.',r.morningDone)),f=>{if(f.has('complete')&&!f.get('action').trim())throw Error('Wähle einen kleinen konkreten Schritt.');save(()=>{const p=dailyPractice(s(),date);Object.assign(p,{goalId:f.get('goalId'),action:f.get('action').trim()});p.ritual={...p.ritual,gratitudeMorning:f.get('gratitudeMorning').trim(),intention:f.get('intention').trim(),obstacle:f.get('obstacle').trim(),trigger:f.get('trigger').trim(),morningDone:f.has('complete')};},'Morgenroutine gespeichert');});}
 function evening(date){const {p,r}=current(date),next=addDays(date,1),tomorrow=s().practice.find(p=>p.date===next);openSheet(form('Dein Abendrückblick',`<p class="subtitle">${date} · Kleine Erfolge zählen. Schwieriges darf bleiben.</p>`+area('action','1 · Welche Handlung hatte ich mir vorgenommen?',p?.action||'')+select('actionStatus','Was ist daraus geworden?',[['planned','Noch offen'],['done','Umgesetzt'],['partial','Teilweise umgesetzt'],['missed','Heute nicht umgesetzt']],p?.actionStatus||'planned')+area('wins','2 · Was habe ich heute erreicht oder gut gemacht?',r.wins)+area('note','Was habe ich gelernt? Was möchte ich anpassen?',p?.note||'')+area('gratitudeEvening','3 · Welchen guten Moment oder welche Unterstützung möchte ich behalten?',r.gratitudeEvening)+area('tomorrowAction',`4 · Meine wichtigste Handlung für morgen (${next})`,tomorrow?.action||r.tomorrowAction||'')+area('tomorrowTrigger','Wann starte ich morgen? Mein Wenn-dann-Plan',tomorrow?.ritual?.trigger||r.tomorrowTrigger||'')+'<p class="hint">Die Handlung für morgen wird in dessen Morgenroutine übernommen. Ein bereits eingetragener Plan wird oben angezeigt und kann hier bewusst angepasst werden.</p>'+box('complete','Mein Abendrückblick ist abgeschlossen.',r.eveningDone)),f=>{const action=f.get('action').trim(),status=f.get('actionStatus'),nextAction=f.get('tomorrowAction').trim();if(['done','partial'].includes(status)&&!action)throw Error('Bitte die Handlung beschreiben.');if(next>today()&&!nextAction&&f.get('tomorrowTrigger').trim())throw Error('Ergänze die Handlung für deinen Plan für morgen.');save(()=>{const p=dailyPractice(s(),date);Object.assign(p,{action,actionStatus:status,note:f.get('note').trim()});p.ritual={...p.ritual,wins:f.get('wins').trim(),gratitudeEvening:f.get('gratitudeEvening').trim(),tomorrowAction:nextAction,tomorrowTrigger:f.get('tomorrowTrigger').trim(),eveningDone:f.has('complete')};if(next>today()&&nextAction){const n=dailyPractice(s(),next);if(n.action!==nextAction)n.actionStatus='planned';n.action=nextAction;n.ritual={...n.ritual,trigger:f.get('tomorrowTrigger').trim()};}},'Abendblick und Plan gespeichert');});}
 function history(p){const r=p?.ritual;if(!r)return '';return `<div class="card"><h3>Morgen & Abend</h3>${[['Tagesimpuls',r.affirmationRead?r.affirmationText:''],['Morgendliche Dankbarkeit',r.gratitudeMorning],['Meine Absicht',r.intention],['Hindernis',r.obstacle],['Wenn-dann-Plan',r.trigger],['Erreicht',r.wins],['Dankbarer Abendmoment',r.gratitudeEvening],['Plan für den nächsten Tag',r.tomorrowAction]].filter(([,v])=>v).map(([k,v])=>`<h4>${k}</h4><p class="goal-prewrap">${esc(v)}</p>`).join('')}<small>${r.affirmationAdopted?'Impuls bewusst übernommen · ':''}${r.morningDone?'Morgenroutine ✓ · ':''}${r.eveningDone?'Abendblick ✓':''}</small></div>`;}
 return {cards,history,click:d=>{if(d.ritual){const date=d.date||today();if(date>today())return c.toast('Die Routine kannst du am jeweiligen Tag öffnen.');({impulse,morning,evening})[d.ritual]?.(date);}},actions:{'ritual-morning':()=>morning(today()),'ritual-evening':()=>evening(today())}};
}
