import test from 'node:test';
import assert from 'node:assert/strict';
import {initial,addTransaction,validate,migrate,balance} from '../model.js';
import {forecast,budgetSummary,searchTransactions} from '../insights.js';
import {normalizeGoal} from '../goals.js';
const date='2026-09-11';
const plan=(id,start,amount,type='expense')=>({id,name:id,start,amount,type,cycle:'once',end:'',stoppedOn:'',account:'bank',category:'Wohnen'});
const tx=(amount,category='Wohnen',extra={})=>({amount,category,type:'expense',date,account:'bank',note:'Miete',...extra});

test('Vorschau erkennt Engpass vor späterem Eingang und filtert Konten',()=>{const s=initial();s.accounts[1].opening=10000;s.schedules.push(plan('miete','2026-09-12',15000),plan('gehalt','2026-09-20',30000,'income'));let f=forecast(s,date);assert.equal(f.lowest,-5000);assert.equal(f.closing,25000);assert.equal(f.rows[1].balance,-5000);assert.equal(forecast(s,date,30,'cash').closing,0);assert.equal(balance(s,'bank'),10000);});
test('Vorschau bucht bezahlt und übersprungen nicht doppelt; Rückstände und Gebühren heute',()=>{const s=initial();s.accounts[1].opening=50000;s.schedules.push(plan('alt','2026-09-01',10000),plan('bezahlt',date,5000),plan('pause',date,3000));s.occurrences.push({schedule:'alt',due:'2026-09-01',skipped:false,fee:1200,note:''},{schedule:'pause',due:date,skipped:true,fee:0,note:''});addTransaction(s,tx(5000,'Wohnen',{schedule:'bezahlt',due:date}));validate(s);const f=forecast(s,date);assert.equal(f.opening,45000);assert.equal(f.closing,33800);assert.equal(f.overdue,1);assert.equal(f.rows[0].items.length,1);});
test('Budgets verwenden nur tatsächliche Monatsausgaben ohne geplante Termine oder Einnahmen',()=>{const s=initial();s.budgets.push({id:'b',category:'Wohnen',amount:10000});s.schedules.push(plan('geplant',date,90000));addTransaction(s,tx(12000));addTransaction(s,tx(90000,'Wohnen',{date:'2026-08-11'}));addTransaction(s,tx(30000,'Wohnen',{type:'income'}));addTransaction(s,tx(2000,'Freizeit'));let b=budgetSummary(s,'2026-09')[0];assert.equal(b.spent,12000);assert.equal(b.left,-2000);assert.equal(b.percent,120);assert.equal(b.tx.length,1);assert.equal(budgetSummary(s,'2026-10')[0].spent,0);});
test('Suche kombiniert Suchwörter, Konto, Kategorie, Datum und Betrag',()=>{const s=initial();addTransaction(s,tx(1250,'Lebensmittel',{note:'Obst Markt'}));addTransaction(s,tx(999,'Freizeit',{account:'cash',note:'Markt'}));assert.equal(searchTransactions(s,'markt 12,50').length,1);assert.equal(searchTransactions(s,'11.09.2026','bank').length,1);assert.equal(searchTransactions(s,'MARKT','cash').length,1);assert.equal(searchTransactions(s,'unbekannt').length,0);});
test('Version 3 sichert neue Bereiche gemeinsam und weist beschädigte Budgets zurück',()=>{const s=initial();s.goals.push(normalizeGoal({id:'g',title:'Zimmer',horizon:'Tag',due:date,done:false,completed:''}));s.beliefs.push({id:'b',text:'Ich beginne klein.',goalId:'g',oldThought:'',evidence:'',archived:false,created:date});s.practice.push({date,readIds:['b'],goalId:'g',action:'10 Minuten',note:'',confidence:3});s.reviews.push({week:'2026-09-07',wins:'Angefangen',learned:'',nextStep:''});s.budgets.push({id:'limit',category:'Wohnen',amount:40000});assert.deepEqual(migrate(JSON.parse(JSON.stringify(s))),s);s.budgets.push({id:'dup',category:'Wohnen',amount:100});assert.throws(()=>validate(s));});
