import {today,uid,cents,addTransaction,balance} from './model.js';
import {cycles,addDays,occurrences,occurrence,setOccurrence,statistics} from './planning.js';
export function financeUI(c) {
  const {esc,eur,icon,input,select,form,openSheet,headerRow,txRows}=c;
  let planFilter='Offen',windowDays=30,visibleRows=50;
  let statFrom=today().slice(0,7)+'-01',statTo=today(),statAccount='all',statCategory=null;
  const state=()=>c.state();
  const close=()=>document.querySelector('#modal').close();
  const label=d=>new Date(d+'T12:00:00').toLocaleDateString('de-DE',{day:'numeric',month:'short',year:'numeric'});
  const rule=id=>state().schedules.find(r=>r.id===id);
  const pending=o=>!['paid','skipped'].includes(o.status);
  function row(o) {
    const status={paid:o.type==='income'?'Eingegangen':'Bezahlt',skipped:'Übersprungen',overdue:`Seit ${o.late} ${o.late===1?'Tag':'Tagen'} fällig`,due:'Heute fällig',planned:'Geplant'}[o.status];
    return `<button class="plan-row" data-plan-detail="${o.schedule}" data-due="${o.due}"><span class="row-icon ${o.type==='income'?'positive':''}">${icon(o.type==='income'?'down':'up')}</span><span class="row-body"><strong>${esc(o.name)}</strong><small>${label(o.due)} · ${cycles[rule(o.schedule).cycle]}</small><span class="status ${o.status}">${status}</span></span><span class="plan-amount ${o.type==='income'?'positive':''}">${o.type==='income'?'+':'−'}${eur(o.amount)}${o.fee?`<small>inkl. ${eur(o.fee)} Gebühren</small>`:''}</span></button>`;
  }
  function planning() {
    const all=occurrences(state(),addDays(today(),windowDays),today());
    const open=all.filter(pending),out=open.filter(o=>o.type==='expense').reduce((n,o)=>n+o.amount,0),inc=open.filter(o=>o.type==='income').reduce((n,o)=>n+o.amount,0),late=open.filter(o=>o.status==='overdue');
    let rows=all.filter(o=>planFilter==='Verlauf'?!pending(o):planFilter==='Abos'?pending(o)&&rule(o.schedule).cycle!=='once':pending(o));
    if(planFilter==='Verlauf')rows.reverse();
    return `<div class="section-head"><div><h2>Zahlungen & Abos</h2><p class="hint">Alles Fällige. Ein klarer nächster Schritt.</p></div><button class="text-button" data-action="new-schedule">+ Planen</button></div><div class="grid2"><div class="card account"><span class="label">Offene Ausgänge</span><strong>${eur(out)}</strong></div><div class="card account"><span class="label">Erwartete Eingänge</span><strong class="positive">${eur(inc)}</strong></div></div><div class="card forecast"><span>Guthaben nach offenen Plänen</span><strong>${eur(state().accounts.reduce((n,a)=>n+balance(state(),a.id),0)+inc-out)}</strong><p class="hint">Heutiges Guthaben plus geplante Eingänge minus offene Ausgänge inkl. Gebühren. Enthält Rückstände und die nächsten ${windowDays} Tage; keine Garantie.</p></div>${late.length?`<div class="notice"><strong>${late.length} ${late.length===1?'Termin ist':'Termine sind'} überfällig</strong><span>Offen bleibt offen, bis du bezahlst oder bewusst überspringst.</span></div>`:''}<div class="range-inline">${select('plan-window','Vorschau',[['30','Nächste 30 Tage'],['90','Nächste 90 Tage'],['365','Nächstes Jahr']],String(windowDays))}</div><div class="tabs">${['Offen','Abos','Verlauf','Serien'].map(f=>`<button data-plan-filter="${f}" class="${f===planFilter?'active':''}">${f}</button>`).join('')}</div>${planFilter==='Serien'?series():`<div class="card plan-list">${rows.slice(0,visibleRows).map(row).join('')||'<p class="empty">Keine Termine in dieser Ansicht.<br>Plane zum Beispiel Miete, Gehalt, Rechnungen oder Abos.</p>'}</div>${rows.length>visibleRows?'<button class="quick secondary wide" data-action="more-plans">Weitere Termine anzeigen</button>':''}`}<p class="hint">„Bezahlt“ / „Eingegangen“ erfasst eine tatsächliche Kontobewegung. Überspringen verändert den Kontostand nicht. Gebühren werden nur von dir eingetragen.</p>`;
  }
  function series(){return state().schedules.map(s=>`<div class="card"><div class="debt-top"><div><h3>${esc(s.name)}</h3><span class="hint">${cycles[s.cycle]} · ${s.type==='income'?'Eingang':'Ausgang'}</span></div><strong>${eur(s.amount)}</strong></div><p class="hint">Ab ${label(s.start)}${s.end?' · Bis '+label(s.end):''}${s.stoppedOn?' · Beendet am '+label(s.stoppedOn):''}</p><button class="tiny" data-schedule-edit="${s.id}">Bearbeiten</button>${!s.stoppedOn?`<button class="tiny danger float-right" data-stop="${s.id}">Serie beenden</button>`:'<span class="pill float-right">Beendet</span>'}</div>`).join('')||'<div class="card"><p class="empty">Lege deine erste geplante Zahlung an.</p></div>';}
  function scheduleForm(id) {
    const s=id?rule(id):null,hasHistory=s&&(state().transactions.some(t=>t.schedule===id)||state().occurrences.some(o=>o.schedule===id));
    openSheet(form(s?'Zahlungsplan bearbeiten':'Eine Zahlung planen',input('name','Name',s?.name||'','text','required maxlength="100" placeholder="Miete, Gehalt, Streaming …"')+select('type','Richtung',[['expense','Ausgabe / Abo'],['income','Erwartete Einnahme']],s?.type||'expense')+input('amount','Betrag je Termin in €',s?(s.amount/100).toFixed(2).replace('.',','):'','text','required inputmode="decimal" placeholder="0,00"')+select('account','Standardkonto',state().accounts.map(a=>[a.id,a.name]),s?.account||'bank')+input('category','Kategorie',s?.category||'Abos & Fixkosten','text','required maxlength="60"')+input('start','Erster Fälligkeitstag',s?.start||today(),'date','required min="2000-01-01" max="2100-12-31"')+select('cycle','Wiederholung',Object.entries(cycles),s?.cycle||'monthly')+input('end','Letzter Fälligkeitstag · optional',s?.end||'','date','min="2000-01-01" max="2100-12-31"')+`<p class="hint">${s?'Änderungen an Betrag, Konto und Kategorie gelten für alle noch offenen Termine. Bereits gebuchte Beträge bleiben erhalten. ':''}${hasHistory?'Beginn, Zyklus, Enddatum und Richtung sind wegen vorhandener Historie gesperrt. ':''}Geplante Beträge verändern dein Guthaben erst beim Erfassen der Zahlung.</p>`),f=>{
      const name=f.get('name').trim(),amount=cents(f.get('amount')),category=f.get('category').trim();if(!name||amount<=0||!category)throw Error('Name, Kategorie und positiver Betrag erforderlich.');
      const next={name,amount,category,account:f.get('account'),type:hasHistory?s.type:f.get('type'),start:hasHistory?s.start:f.get('start'),cycle:hasHistory?s.cycle:f.get('cycle'),end:hasHistory?s.end:f.get('end')};
      if(c.commit(()=>{if(s)Object.assign(rule(id),next);else state().schedules.push({id:uid(),...next,stoppedOn:''});},'Zahlungsplan gespeichert'))close();
    });if(hasHistory)for(const id of ['type','start','cycle','end'])document.getElementById(id).disabled=true;
  }
  function detail(id,due) {
    const s=rule(id),o=occurrence(state(),s,due,today());
    openSheet(`<p class="eyebrow">${cycles[s.cycle]} · ${s.type==='income'?'ERWARTETER EINGANG':'ZAHLUNG'}</p><h1 class="sheet-title">${esc(s.name)}</h1><p class="subtitle">Fällig am ${label(due)}</p><div class="card"><div class="debt-top"><span>Gesamtbetrag</span><strong>${eur(o.amount)}</strong></div>${o.fee?`<p class="hint">Enthaltene Mahngebühren: ${eur(o.fee)}</p>`:''}${o.status==='overdue'?`<p class="negative">Seit ${o.late} ${o.late===1?'Tag':'Tagen'} überfällig</p>`:''}${o.note?`<p class="hint">${esc(o.note)}</p>`:''}</div>${o.tx?`<span class="pill">${s.type==='income'?'Eingegangen':'Bezahlt'} am ${label(o.tx.date)}</span><p class="hint">Gebucht auf ${esc(state().accounts.find(a=>a.id===o.tx.account)?.name)}.</p><button class="primary" data-plan-undo="${o.tx.id}">Zahlung rückgängig machen</button>`:o.status==='skipped'?`<p class="hint">Diesen Termin hast du übersprungen. Die restliche Serie läuft weiter.</p><button class="primary" data-reopen="${id}" data-due="${due}">Termin wieder öffnen</button>`:`<button class="primary" data-plan-pay="${id}" data-due="${due}">${s.type==='income'?'Als eingegangen erfassen':'Als bezahlt erfassen'}</button><div class="grid2" style="margin-top:12px"><button class="quick secondary" data-skip="${id}" data-due="${due}">Überspringen</button>${s.type==='expense'?`<button class="quick secondary" data-fee="${id}" data-due="${due}">Mahngebühren</button>`:''}</div><p class="hint">Kein Geldtransfer: Hier dokumentierst du eine Zahlung, die du tatsächlich vorgenommen oder erhalten hast.</p>`}`);
  }
  function pay(id,due) {
    const s=rule(id),o=occurrence(state(),s,due,today());
    openSheet(form(s.type==='income'?'Eingang bestätigen':'Zahlung bestätigen',`<div class="card"><h3>${esc(s.name)}</h3><h2>${eur(o.amount)}</h2><p class="hint">Termin ${label(due)}${o.fee?' · inkl. '+eur(o.fee)+' Mahngebühren':''}</p></div>`+select('account','Tatsächliches Konto',state().accounts.map(a=>[a.id,a.name]),s.account)+input('date','Tatsächliches Zahlungsdatum',today(),'date','required')+input('note','Notiz',s.name,'text','maxlength="160"'),'Jetzt buchen'),f=>{if(f.get('date')>today())throw Error('Das Zahlungsdatum darf nicht in der Zukunft liegen.');if(c.commit(()=>addTransaction(state(),{type:s.type,amount:o.amount,account:f.get('account'),date:f.get('date'),category:s.category,note:f.get('note').trim(),schedule:id,due}),'Zahlung gebucht'))close();});
  }
  function fee(id,due) {
    const s=rule(id),o=occurrence(state(),s,due,today());
    openSheet(form('Mahngebühren eintragen',`<p class="subtitle">${esc(s.name)} · ${label(due)}</p>`+input('fee','Gesamte Mahngebühren dieses Termins in €',(o.fee/100).toFixed(2).replace('.',','),'text','required inputmode="decimal"')+input('note','Notiz / Mahnung',o.note,'text','maxlength="300"')+'<p class="hint">Trage die tatsächlich mitgeteilten Gebühren ein. Der Betrag ersetzt die bisher erfassten Gebühren dieses Termins. Keine automatische Berechnung.</p>'),f=>{const amount=cents(f.get('fee'));if(amount<0)throw Error('Gebühren dürfen nicht negativ sein.');if(c.commit(()=>setOccurrence(state(),id,due,{fee:amount,note:f.get('note').trim()}),'Gebühren gespeichert'))close();});
  }
  function stop(id){openSheet(`<h1 class="sheet-title">Serie beenden?</h1><p class="subtitle">${esc(rule(id).name)}</p><p class="hint">Nach heute entstehen keine neuen Termine. Bereits fällige, bezahlte und übersprungene Termine bleiben erhalten. Ein Abo beim Anbieter wird dadurch nicht gekündigt.</p><button class="primary" data-stop-confirm="${id}">Ab heute keine neuen Termine</button>`);}
  function stats() {
    const r=statistics(state(),statFrom,statTo,statAccount),span=Math.max(1,Math.round((Date.parse(statTo)-Date.parse(statFrom))/86400000)+1);
    return headerRow('Deine Statistik')+`<p class="subtitle">Verstehe, wohin dein Geld geht. Tippe eine Kategorie für alle zugehörigen Buchungen an.</p><div class="tabs">${['Monat','Letzter Monat','Jahr','Alles'].map(x=>`<button data-stat-period="${x}">${x}</button>`).join('')}</div><div class="grid2 stat-dates"><div>${input('stat-from','Von',statFrom,'date')}</div><div>${input('stat-to','Bis',statTo,'date')}</div></div>${select('stat-account','Konto',[['all','Alle Konten'],...state().accounts.map(a=>[a.id,a.name])],statAccount)}<div class="grid2" style="margin-top:20px"><button class="card account" data-stat-list="income"><span class="label">Einnahmen ↗</span><strong class="positive">${eur(r.income)}</strong></button><button class="card account" data-stat-list="expense"><span class="label">Ausgaben ↗</span><strong>${eur(r.expense)}</strong></button></div><div class="card"><div class="debt-top"><div><h3>Überschuss im Zeitraum</h3><span class="hint">Einnahmen minus Ausgaben</span></div><strong class="${r.net<0?'negative':'positive'}">${eur(r.net)}</strong></div><div class="stats-meta"><span><b>${r.rate===null?'—':r.rate.toFixed(1).replace('.',',')+' %'}</b>Überschussquote</span><span><b>${eur(Math.round(r.expense/span))}</b>Ausgaben / Tag</span><span><b>${r.tx.length}</b>Buchungen</span></div></div>`+headerRow('Ausgaben nach Kategorie')+`<div class="card">${r.categories.map(([cat,amount])=>`<button class="category-row" data-stat-cat="${esc(cat)}"><span><strong>${esc(cat)}</strong><b>${eur(amount)} &nbsp; ›</b></span><div class="progress"><span style="width:${r.expense?amount/r.expense*100:0}%"></span></div><small>${r.expense?(amount/r.expense*100).toFixed(1).replace('.',','):0} % der Ausgaben</small></button>`).join('')||'<p class="empty">Keine Ausgaben im gewählten Zeitraum.</p>'}</div>`+headerRow('Monate im Vergleich')+monthly(r.tx)+`<p class="hint">Statistik berücksichtigt tatsächliche Buchungen nach Zahlungsdatum. Pläne und übersprungene Termine zählen nicht mit. Gebühren sind in der Kategorie ihrer Zahlung enthalten. Kontostand-Korrekturen zählen nicht als Einnahme.</p>`;
  }
  function monthly(tx){const months={};for(const t of tx){const m=t.date.slice(0,7);months[m]??={income:0,expense:0};months[m][t.type]+=t.amount;}const entries=Object.entries(months).sort(([a],[b])=>b.localeCompare(a));return `<div class="card">${entries.map(([m,v])=>`<button class="month-row" data-stat-month="${m}"><strong>${new Date(m+'-01T12:00:00').toLocaleDateString('de-DE',{month:'long',year:'numeric'})}</strong><span class="positive">+${eur(v.income)}</span><span>−${eur(v.expense)} ›</span></button>`).join('')||'<p class="empty">Noch keine Buchungen.</p>'}</div>`;}
  function statList(kind,category) {const r=statistics(state(),statFrom,statTo,statAccount),tx=r.tx.filter(t=>(!kind||t.type===kind)&&(!category||t.category===category));openSheet(`<h1 class="sheet-title">${esc(category||(kind==='income'?'Einnahmen':'Ausgaben'))}</h1><p class="subtitle">${label(statFrom)} – ${label(statTo)} · ${tx.length} Buchungen</p><div class="card">${txRows(tx.sort((a,b)=>b.date.localeCompare(a.date)))}</div>`);}
  function period(p){const y=today().slice(0,4),m=today().slice(0,7);if(p==='Monat'){statFrom=m+'-01';statTo=today()}if(p==='Letzter Monat'){statTo=addDays(m+'-01',-1);statFrom=statTo.slice(0,7)+'-01'}if(p==='Jahr'){statFrom=y+'-01-01';statTo=today()}if(p==='Alles'){statFrom=state().transactions.map(t=>t.date).sort()[0]||today();statTo=today()}c.render();}
  const actions={'new-schedule':()=>scheduleForm(),'more-plans':()=>{visibleRows+=50;c.render()}};
  function click(d) {
    if(d.planFilter){planFilter=d.planFilter;visibleRows=50;c.render()}
    if(d.planDetail)detail(d.planDetail,d.due);if(d.scheduleEdit)scheduleForm(d.scheduleEdit);
    if(d.planPay)pay(d.planPay,d.due);if(d.fee)fee(d.fee,d.due);
    if(d.skip||d.reopen){if(c.commit(()=>setOccurrence(state(),d.skip||d.reopen,d.due,{skipped:!!d.skip}),d.skip?'Termin übersprungen':'Termin wieder geöffnet'))close()}
    if(d.planUndo){c.removeEntry('transactions',d.planUndo);close()}
    if(d.stop)stop(d.stop);if(d.stopConfirm){if(c.commit(()=>rule(d.stopConfirm).stoppedOn=today(),'Serie beendet'))close()}
    if(d.statPeriod)period(d.statPeriod);if(d.statCat)statList('expense',d.statCat);if(d.statList)statList(d.statList);
    if(d.statMonth){statFrom=d.statMonth+'-01';const next=new Date(statFrom+'T12:00:00Z');next.setUTCMonth(next.getUTCMonth()+1);statTo=addDays(next.toISOString().slice(0,10),-1);c.render()}
  }
  function change(e) {
    if(e.target.id==='plan-window'){windowDays=Number(e.target.value);visibleRows=50;c.render()}
    if(['stat-from','stat-to','stat-account'].includes(e.target.id)){const from=document.querySelector('#stat-from').value,to=document.querySelector('#stat-to').value;if(!from||!to||from>to){c.toast('Bitte einen gültigen Zeitraum wählen.');return}statFrom=from;statTo=to;statAccount=document.querySelector('#stat-account').value;c.render()}
  }
  return {planning,stats,actions,click,change};
}
